In [1]:
# !pip install spacy

In [2]:
import spacy
# !python -m spacy download en_core_web_lg

In [3]:
import spacy

# !pip install spacy
# pip install -U spacy

In [4]:
nlp = spacy.load("en_core_web_lg")

In [5]:
doc = nlp("dog cat banana jkfgsjg")

for token in doc:
  print(token.text, "vector:", token.has_vector, "OOV:", token.is_oov)

dog vector: True OOV: False
cat vector: True OOV: False
banana vector: True OOV: False
jkfgsjg vector: False OOV: True


In [6]:
doc[0]

dog

In [7]:
# dog
doc[0].vector

array([ 1.2330e+00,  4.2963e+00, -7.9738e+00, -1.0121e+01,  1.8207e+00,
        1.4098e+00, -4.5180e+00, -5.2261e+00, -2.9157e-01,  9.5234e-01,
        6.9880e+00,  5.0637e+00, -5.5726e-03,  3.3395e+00,  6.4596e+00,
       -6.3742e+00,  3.9045e-02, -3.9855e+00,  1.2085e+00, -1.3186e+00,
       -4.8886e+00,  3.7066e+00, -2.8281e+00, -3.5447e+00,  7.6888e-01,
        1.5016e+00, -4.3632e+00,  8.6480e+00, -5.9286e+00, -1.3055e+00,
        8.3870e-01,  9.0137e-01, -1.7843e+00, -1.0148e+00,  2.7300e+00,
       -6.9039e+00,  8.0413e-01,  7.4880e+00,  6.1078e+00, -4.2130e+00,
       -1.5384e-01, -5.4995e+00,  1.0896e+01,  3.9278e+00, -1.3601e-01,
        7.7732e-02,  3.2218e+00, -5.8777e+00,  6.1359e-01, -2.4287e+00,
        6.2820e+00,  1.3461e+01,  4.3236e+00,  2.4266e+00, -2.6512e+00,
        1.1577e+00,  5.0848e+00, -1.7058e+00,  3.3824e+00,  3.2850e+00,
        1.0969e+00, -8.3711e+00, -1.5554e+00,  2.0296e+00, -2.6796e+00,
       -6.9195e+00, -2.3386e+00, -1.9916e+00, -3.0450e+00,  2.48

In [8]:
doc[0].vector.shape

(300,)

In [9]:
# cat
doc[1].vector

array([ 3.7032e+00,  4.1982e+00, -5.0002e+00, -1.1322e+01,  3.1702e-02,
       -1.0255e+00, -3.0870e+00, -3.7327e+00,  5.3875e-01,  3.5679e+00,
        6.9276e+00,  1.5793e+00,  5.1188e-01,  3.1868e+00,  6.1534e+00,
       -4.8941e+00, -2.9959e-01, -3.6276e+00,  2.3825e+00, -1.4402e+00,
       -4.7577e+00,  4.3607e+00, -4.9814e+00, -3.6672e+00, -1.8052e+00,
       -2.1888e+00, -4.2875e+00,  5.5712e+00, -5.2875e+00, -1.8346e+00,
       -2.2015e+00, -7.7091e-01, -4.8260e+00,  1.2464e+00, -1.7945e+00,
       -8.1280e+00,  1.9994e+00,  1.1413e+00,  3.8032e+00, -2.8783e+00,
       -4.2136e-01, -4.4177e+00,  7.7456e+00,  4.9535e+00,  1.7402e+00,
        1.8275e-01,  2.4218e+00, -3.1496e+00, -3.8057e-02, -2.9818e+00,
        8.3396e-01,  1.1531e+01,  3.5684e+00,  2.5970e+00, -2.8438e+00,
        3.2755e+00,  4.5674e+00,  3.2219e+00,  3.4206e+00,  1.1200e-01,
        1.0303e-01, -5.8396e+00,  4.6370e-01,  2.7750e+00, -5.3713e+00,
       -5.0247e+00, -2.0212e+00,  5.8772e-01,  1.1569e+00,  1.32

In [10]:
# jkfgsjg
doc[3].vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [11]:
base_token = nlp("sandwich")
base_token.vector.shape

(300,)

In [12]:
doc = nlp("bread sandwich burger car tiger human rice food")

for token in doc:
  print(f"{token.text} <-> {base_token.text}:", token.similarity(base_token))

bread <-> sandwich: 0.6341067177397708
sandwich <-> sandwich: 0.9999999823146835
burger <-> sandwich: 0.7900927171273502
car <-> sandwich: 0.1825516115154349
tiger <-> sandwich: 0.11234833779127572
human <-> sandwich: -0.042971608984131424
rice <-> sandwich: 0.4838404599332193
food <-> sandwich: 0.43480639682629374


In [13]:
def similar_words(base_word, word_to_compare):
  base_token = nlp(base_word)
  doc = nlp(word_to_compare)
  for token in doc:
      print(f"{token.text} <-> {base_token.text}:", token.similarity(base_token))


In [14]:
similar_words("iphone", "apple samsung iphone dog cat banana")

apple <-> iphone: 0.4387907748060368
samsung <-> iphone: 0.6708590303423401
iphone <-> iphone: 0.9999999983096304
dog <-> iphone: 0.08211864228011527
cat <-> iphone: 0.11430552710784589
banana <-> iphone: 0.19108547187460106


In [15]:
king = nlp.vocab["king"].vector
man = nlp.vocab["man"].vector
woman = nlp.vocab["woman"].vector
queen = nlp.vocab["queen"].vector

result = king - man + woman

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([result], [queen])

array([[0.6178014]], dtype=float32)

In [17]:
france = nlp.vocab["France"].vector
paris = nlp.vocab["Paris"].vector
berlin = nlp.vocab["Berlin"].vector
germany = nlp.vocab["Germany"].vector

result = france - paris + berlin

cosine_similarity([result], [germany])

# France - Paris + Berlin = Germany

array([[0.8555053]], dtype=float32)

# NLP: Text Classification using Spacy word Embeddings

# end-to-end project: fake and real news data

In [18]:
import pandas as pd

true_df = pd.read_csv("D:\Fake And Real News predection\\notebooks\\data\\Fake.csv")
false_df = pd.read_csv("D:\Fake And Real News predection\\notebooks\\data\\True.csv")


In [19]:
true_df['class'] = 1
false_df['class'] = 0

df = pd.concat([true_df,false_df])

In [20]:
df.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  class  
0  December 31, 2017      1  
1  December 31, 2017      1  
2  December 30, 2017      1  
3  December 29, 2017      1  
4  December 25, 2017      1

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44898 entries, 0 to 21416
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   date     44898 non-null  object
 4   class    44898 non-null  int64 
dtypes: int64(1), object(4)
memory usage: 2.1+ MB


In [ ]:
#print dataframe
df.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      1  
1  December 31, 2017      1  
2  December 30, 2017      1  
3  December 29, 2017      1  
4  December 25, 2017      1  
5  December 25, 2017      1  
6  December 23, 2017      1  
7  December 23, 2017      1  
8  December 22, 2017      1  
9  December 21, 2017      1

In [23]:
print(df.shape)

(44898, 5)


In [24]:
#check imbalance in data set
# check the distribution of data in our dataset
df['class'].value_counts()

# df["class"].value_counts()

class
1    23481
0    21417
Name: count, dtype: int64

In [25]:
print(df.head(10))

                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

In [26]:
df["text"]

0        Donald Trump just couldn t wish all Americans ...
1        House Intelligence Committee Chairman Devin Nu...
2        On Friday, it was revealed that former Milwauk...
3        On Christmas day, Donald Trump announced that ...
4        Pope Francis used his annual Christmas Day mes...
                               ...                        
21412    BRUSSELS (Reuters) - NATO allies on Tuesday we...
21413    LONDON (Reuters) - LexisNexis, a provider of l...
21414    MINSK (Reuters) - In the shadow of disused Sov...
21415    MOSCOW (Reuters) - Vatican Secretary of State ...
21416    JAKARTA (Reuters) - Indonesia will buy 11 Sukh...
Name: text, Length: 44898, dtype: object

In [28]:
import spacy
!python -m spacy download en_core_web_lg
nlp = spacy.load("en_core_web_lg")

In [ ]:
df['text'].dtypes

dtype('O')

In [ ]:
# Convert text to vector

df['vector'] = df['text'].apply(lambda text: nlp(text).vector)

In [ ]:
len(df)

20800

In [ ]:
print(df.head())

   id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  label_num  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1        NaN  
1  Ever get the feeling your life circles the rou...      0        NaN  
2  Why the Truth Might Get You Fired October 29, ...      1        NaN  
3  Videos 15 Civilians Killed In Single US Airstr...      1        NaN  
4  Print \nAn Iranian woman has been sentenced to...      1        NaN  


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split (
    df.vector.values,
    df.label_num,
    test_size = 0.2,
    random_state = 42
)

AttributeError: 'DataFrame' object has no attribute 'vector'

In [ ]:
X_train.shape

NameError: name 'X_train' is not defined

In [ ]:
X_test.shape

: 

In [ ]:
import numpy as np

X_train_stack = np.stack(X_train)
X_test_stack = np.stack(X_test)


NameError: name 'X_train' is not defined

In [ ]:
print(X_train_stack.shape)
print(X_test_stack.shape)

NameError: name 'X_train_stack' is not defined

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_stack_sc = scaler.fit_transform(X_train_stack)
X_test_stack_sc = scaler.transform(X_test_stack)


model.fit(X_train_stack_sc, y_train)

NameError: name 'X_train_stack' is not defined

In [ ]:
y_pred = model.predict(X_test_stack_sc)
y_pred

NameError: name 'X_test_stack_sc' is not defined

In [ ]:
y_test

: 

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

: 

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

: 

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

: 

In [ ]:
model = MultinomialNB(alpha = 0.1)
model.fit(X_train_stack_sc, y_train)

: 

In [ ]:
import numpy as np
sc = []
for alpha in np.arange(0,1,0.1):   # 0, 0.1, 0.2, 0.3, ....1
  model =  MultinomialNB(alpha = alpha)
  model.fit(X_train, y_train)
  model.predict(X_test)
  sc1 = accuracy_score(y_test, y_pred)
  sc.append(sc1)

: 

In [ ]:
# Gensim to conduct word2vec
import gensim.downloader as api
# This is a huge model (~1.6 gb) and it will take some time to load

wv = api.load('word2vec-google-news-300')

: 

In [ ]:
wv.similarity("great", "good")

: 

In [ ]:
wv.similarity("profit", "loss")

: 

In [ ]:
wv.most_similar("good", topn = 3)

: 

In [ ]:
wv.most_similar("Dog")

: 

: 

In [ ]:
# King - man + woman = Queen

wv.most_similar(positive = ['King', 'woman'], negative = ['man'])

: 

In [ ]:
# France - Paris + Berlin = Germany
wv.most_similar(positive = ['France', 'Berlin'], negative = ['Paris'], topn = 3)

: 

In [ ]:
wv.doesnt_match(["facebook", "google", "cat", "microsoft"])

: 

In [ ]:
wv.doesnt_match(["facebook", "mouse", "cat", "dog"])

: 

In [ ]:
# Glove
glv = api.load('glove-twitter-25')

: 

In [ ]:
print(glv.most_similar("good"))
print(glv.most_similar("profit"))


: 

In [ ]:
glv.doesnt_match(["facebook", "google", "cat", "microsoft"])

: 

In [ ]:
glv.doesnt_match("facebook google cat microsoft".split())

: 

: 